# Generated by Django 3.2.18 on 2023-04-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_news_emotional_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='story_id',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
