# Generated by Django 4.2 on 2023-04-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_comment_emotional_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
