# Generated by Django 4.2 on 2023-04-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_news_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regions_content',
            fields=[
                ('region_content_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=200)),
                ('region_tonality', models.FloatField(default=0)),
                ('region_color', models.CharField(default='#FFFFFF', max_length=10)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Regions_source',
            fields=[
                ('region_source_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=200)),
                ('region_tonality', models.FloatField(default=0)),
                ('region_color', models.CharField(default='#FFFFFF', max_length=10)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='content_region',
            new_name='region_content_name',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='source_region',
            new_name='region_source_name',
        ),
        migrations.AddField(
            model_name='news',
            name='region_content_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='news_content_region', to='myapp.regions_content'),
        ),
        migrations.AddField(
            model_name='news',
            name='region_source_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='news_source_region', to='myapp.regions_source'),
        ),
    ]
