# Generated by Django 4.2 on 2023-04-22 15:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_stopword'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_source', models.BooleanField(default=False)),
                ('is_content', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=200)),
                ('region_tonality', models.FloatField(default=0)),
                ('region_color', models.CharField(default='#FFFFFF', max_length=10)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='region_content_name',
            new_name='content_region_name',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='region_source_name',
            new_name='source_region_name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='region_content_code',
        ),
        migrations.RemoveField(
            model_name='news',
            name='region_source_code',
        ),
        migrations.AlterField(
            model_name='news',
            name='emotional_tone',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Regions_content',
        ),
        migrations.DeleteModel(
            name='Regions_source',
        ),
        migrations.AddField(
            model_name='newsregion',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.news'),
        ),
        migrations.AddField(
            model_name='newsregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_regions', to='myapp.region'),
        ),
        migrations.AddField(
            model_name='news',
            name='regions',
            field=models.ManyToManyField(related_name='news', through='myapp.NewsRegion', to='myapp.region'),
        ),
        migrations.AlterUniqueTogether(
            name='newsregion',
            unique_together={('news', 'region')},
        ),
    ]
