# Generated by Django 4.2 on 2023-04-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_region_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
