# Generated by Django 4.2 on 2023-08-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_gates_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='gates',
            name='number_of_entries',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
