# Generated by Django 5.1.7 on 2025-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_featuredgates'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
