# Generated by Django 5.1.7 on 2025-03-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_searchsuggestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True, null=True)),
                ('is_ignore', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
