# Generated by Django 5.1.7 on 2025-06-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_telegrambotuser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredgates',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gates',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
