# Generated by Django 5.1.7 on 2025-08-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_featuredgates_icon_gates_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredgates',
            name='image',
        ),
        migrations.AddField(
            model_name='featuredgates',
            name='is_special',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
