# Generated by Django 5.1.7 on 2025-08-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_remove_featuredgates_image_featuredgates_is_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredgates',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
