# Generated by Django 5.1.7 on 2025-08-31 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_alter_featuredgates_is_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='device_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
