# Generated by Django 5.1.7 on 2025-08-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_users_device_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredgates',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='featuredgates',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
