# Generated by Django 5.1.7 on 2025-09-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_alter_featuredgates_options_featuredgates_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='device_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_id',
            field=models.TextField(default='none'),
        ),
    ]
