# Generated by Django 5.1.7 on 2025-10-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_publishingproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishingproject',
            name='published_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
