# Generated by Django 5.1.7 on 2025-10-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_publishingproject_published_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishingproject',
            name='project_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
