# Generated by Django 3.2.18 on 2023-04-05 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.AddField(
            model_name='news',
            name='content_region',
            field=models.CharField(default='Неизвестно', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='country',
            field=models.CharField(default='Неизвестно', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='document_type',
            field=models.CharField(default='Неизвестно', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='event_type',
            field=models.CharField(default='Неизвестно', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='persons',
            field=models.CharField(default='Неизвестно', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='news',
            name='source_region',
            field=models.CharField(default='Неизвестно', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='story_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='Неизвестно', max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(default='Неизвестно', max_length=200),
        ),
    ]
