# Generated by Django 3.2.18 on 2023-04-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230405_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='emotional_tone',
            field=models.CharField(default='Неизвестно', max_length=20),
        ),
    ]
