# Generated by Django 4.2 on 2023-04-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='source',
        ),
        migrations.AlterField(
            model_name='comment',
            name='emotional_tone',
            field=models.CharField(max_length=20),
        ),
    ]
