# Generated by Django 4.2 on 2023-04-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_comment_emotional_tone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='emotional_tone',
            field=models.CharField(choices=[('положительно', 'положительно'), ('негативно', 'негативно'), ('нейтрально', 'нейтрально'), ('skip', 'skip')], default='skip', max_length=15),
        ),
    ]
