# Generated by Django 4.2 on 2023-04-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_regions_content_regions_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='region_content_code',
        ),
        migrations.RemoveField(
            model_name='news',
            name='region_source_code',
        ),
    ]
