# Generated by Django 4.2 on 2023-04-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_newsregion_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='regions',
        ),
        migrations.AddField(
            model_name='news',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='myapp.region'),
        ),
        migrations.DeleteModel(
            name='NewsRegion',
        ),
    ]
