# Generated by Django 4.2 on 2023-05-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downloads',
            name='gate_app',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='downloads',
            name='who',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Gate',
        ),
    ]
