# Generated by Django 4.2 on 2023-05-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_downloads_gate_app_alter_downloads_who_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloads',
            name='who',
        ),
        migrations.AddField(
            model_name='downloads',
            name='as_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='asname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='continent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='continentCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='countryCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='error_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='hosting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='if_game',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='isp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='mobile',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='proxy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='regionName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='reverse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='downloads',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
