# Generated by Django 4.2 on 2023-05-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_downloads_who_downloads_as_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='org',
            field=models.TextField(blank=True, null=True),
        ),
    ]
