# Generated by Django 4.2 on 2023-06-20 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_downloads_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('event_name', models.CharField(max_length=50)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('continent', models.CharField(blank=True, max_length=50, null=True)),
                ('continentCode', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('countryCode', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('regionName', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('isp', models.TextField(blank=True, null=True)),
                ('as_info', models.TextField(blank=True, null=True)),
                ('asname', models.TextField(blank=True, null=True)),
                ('reverse', models.TextField(blank=True, null=True)),
                ('org', models.TextField(blank=True, null=True)),
                ('mobile', models.BooleanField(blank=True, null=True)),
                ('proxy', models.BooleanField(blank=True, null=True)),
                ('hosting', models.BooleanField(blank=True, null=True)),
                ('error_msg', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
