# Generated by Django 4.2 on 2023-06-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_gates'),
    ]

    operations = [
        migrations.AddField(
            model_name='gates',
            name='resource_pack',
            field=models.TextField(blank=True, default=None),
        ),
    ]
